# -*- coding: utf-8 -*-
import os
import re

def decode_gbk_as_utf8(text):
    """尝试将UTF-8解码的乱码转换回正确的中文"""
    try:
        return text.encode('latin1').decode('gbk')
    except:
        return text

def fix_file(filepath):
    """修复单个Vue文件的编码问题"""
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()
    
    original = content
    
    replacements = {
        '銆?': '',
        '銆': '',
        '娴?': '错',
        '澶?': '败',
        '闂?': '问',
        '闃?': '题',
        '锅?': '错',
        '閿?': '错',
        '閸?': '错',
        '浠?': '错',
        '涓?': '错',
        '鎵?': '错',
        '闀?': '错',
        '鎻?': '错',
        '鏍?': '错',
        '閿?': '请',
        '鍖?': '请',
        '闅?': '请',
        '閼?': '请',
        '閿?': '查',
        '浠?': '查',
        '閼?': '验',
        '閸?': '验',
        '浼?': '验',
        '鏍?': '统',
        '閿?': '询',
        '閼?': '询',
        '閿?': '重',
        '閼?': '试',
        '浠?': '试',
        '浼?': '试',
        '娴?': '获取',
        '娴?': '获取',
        '澶?': '状态',
        '闂?': '状态',
        '闃?': '异常',
        '娴?': '导入',
        '娴?': '导入',
        '鎵?': '导出',
        '鍙?': '导出',
        '闃?': '加载',
        '浠?': '加载',
        '閼?': '加载',
        '闂?': '获取',
        '闃?': '获取',
        '鎵?': '失败',
        '鍖?': '失败',
        '闅?': '失败',
        '浼?': '失败',
        '娴?': '操作',
        '娴?': '操作',
        '闃?': '请求',
        '闀?': '请求',
        '閼?': '请求',
        '浠?': '解析',
        '浼?': '解析',
        '闃?': '分类',
        '闀?': '分类',
        '鎻?': '进入',
        '鍖?': '进入',
        '闅?': '进入',
        '娴?': '会话',
        '娴?': '会话',
        '澶?': '事件',
        '闂?': '事件',
        '闃?': '事件',
        '鎵?': '配置',
        '鍙?': '配置',
        '闀?': '配置',
        '閿?': '统计',
        '閼?': '统计',
        '涓?': '统计',
        '閸?': '事件',
        '閼?': '事件',
        '閿?': '问题',
        '浠?': '问题',
        '閼?': '问题',
        '闃?': '问题',
        '闀?': '问题',
        '鎻?': '数据',
        '鍖?': '数据',
        '闅?': '数据',
        '娴?': '分析',
        '娴?': '分析',
        '澶?': '规则',
        '闂?': '规则',
        '闃?': '规则',
        '闃?': '税务',
        '闀?': '税务',
        '浼?': '税务',
        '闃?': '财务',
        '闀?': '财务',
        '閿?': '服务',
        '閼?': '服务',
        '涓?': '服务',
        '娴?': '检测',
        '娴?': '检测',
        '澶?': '证书',
        '闂?': '证书',
        '闃?': '证书',
        '闃?': '证书',
        '闀?': '证书',
        '浼?': '证书',
        '娴?': '访问',
        '娴?': '访问',
        '澶?': '上传',
        '闂?': '上传',
        '闃?': '上传',
        '闀?': '上传',
        '浼?': '上传',
        '鎵?': '下载',
        '鍙?': '下载',
        '闀?': '下载',
        '闃?': '下载',
        '闀?': '下载',
        '浼?': '下载',
        '娴?': '登录',
        '娴?': '登录',
        '澶?': '注册',
        '闂?': '注册',
        '闃?': '注册',
        '闀?': '注册',
        '浼?': '注册',
        '闃?': '搜索',
        '闀?': '搜索',
        '浼?': '搜索',
        '娴?': '登记',
        '娴?': '登记',
        '澶?': '图像',
        '闂?': '图像',
        '闃?': '图像',
        '闀?': '图像',
        '浼?': '图像',
        '闃?': '严重',
        '闀?': '严重',
        '浼?': '严重',
        '娴?': '信息',
        '娴?': '信息',
        '澶?': '提示',
        '闂?': '提示',
        '闃?': '提示',
        '闀?': '提示',
        '浼?': '提示',
        '闃?': '审计',
        '闀?': '审计',
        '浼?': '审计',
        '娴?': '管理',
        '娴?': '管理',
        '澶?': '通知',
        '闂?': '通知',
        '闃?': '通知',
        '闀?': '通知',
        '浼?': '通知',
        '闃?': '管理',
        '闀?': '管理',
        '浼?': '管理',
        '娴?': '智能',
        '娴?': '智能',
        '澶?': '体化',
        '闂?': '体化',
        '闃?': '体化',
        '闀?': '体化',
        '浼?': '体化',
        '娴?': '任务',
        '娴?': '任务',
        '澶?': '任务',
        '闂?': '任务',
        '闃?': '任务',
        '闀?': '任务',
        '浼?': '任务',
        '娴?': '记录',
        '娴?': '记录',
        '澶?': '记录',
        '闂?': '记录',
        '闃?': '记录',
        '闀?': '记录',
        '浼?': '记录',
        '娴?': '处理',
        '娴?': '处理',
        '澶?': '处理',
        '闂?': '处理',
        '闃?': '处理',
        '闀?': '处理',
        '浼?': '处理',
    }
    
    for wrong, correct in replacements.items():
        content = content.replace(wrong, correct)
    
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

def main():
    views_dir = r'd:\Python\Codebase\My_rag\rag_frontend\src\views'
    
    vue_files = [
        'AuditResultView.vue',
        'ChatLogsView.vue',
        'ContractReviewView.vue',
        'EnterpriseView.vue',
        'FinancialDataEntryView.vue',
        'FinancialHealthView.vue',
        'HITLApprovalView.vue',
        'IntentClassifierDebugView.vue',
        'KnowledgeManagementView.vue',
        'ModernChatView.vue',
        'ModernDocumentsView.vue',
        'ModernKnowledgeDetailView.vue',
        'ModernLoginView.vue',
        'ModernProfileView.vue',
        'ModernRegisterView.vue',
        'ModernSearchView.vue',
        'ModernUploadView.vue',
        'MultiAgentChatView.vue',
        'PolicyNotificationView.vue',
        'PolicySearchView.vue',
        'ReviewDashboard.vue',
        'SecurityAuditView.vue',
        'TaskManagementView.vue',
        'TaxIntelligenceView.vue',
        'TaxReportUploadView.vue',
        'TaxSubmissionView.vue',
        'TestDataGuideView.vue',
        'NotificationCenterView.vue',
    ]
    
    fixed_count = 0
    for filename in vue_files:
        filepath = os.path.join(views_dir, filename)
        if os.path.exists(filepath):
            if fix_file(filepath):
                print(f'Fixed: {filename}')
                fixed_count += 1
            else:
                print(f'No changes: {filename}')
    
    print(f'\nDone! Fixed {fixed_count} files.')

if __name__ == '__main__':
    main()
